
dist: xenial

os: linux

language: ruby

cache: bundler

rvm:
 - 2.3.3

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update  
  - sudo apt-get install unixodbc-dev
  - sudo docker pull microsoft/mssql-server-linux  
  - sudo docker run --name dbserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Rsp3cRsp3c' -ti -p 1433:1433 -d microsoft/mssql-server-linux
  - sudo docker ps -a
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - wget http://www.freetds.org/files/stable/freetds-1.00.21.tar.gz
  - tar -xzf freetds-1.00.21.tar.gz
  - cd freetds-1.00.21
  - ./configure --prefix=/usr/local --with-tdsver=7.3
  - make
  - sudo make install

install:
  - travis_wait 20 mvn install
  - bundle install
  - bundle exec rake db:setup RAILS_ENV=test --trace




  