# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

staging:
  secret_key_base: 8eab8afb147d5986719d388e696165512cfa45c1a7c4091f5ac6469579ff18da8c425a4a189a151e0ec2096ed58d6e99b5709f16bbf3d5cad92b9c4886060687

development:
  secret_key_base: 8eab8afb147d5986719d388e696165512cfa45c1a7c4091f5ac6469579ff18da8c425a4a189a151e0ec2096ed58d6e99b5709f16bbf3d5cad92b9c4886060687

preproduction:
  secret_key_base: a36204f63402e32db0f8207bd5439aa3291e05374f6fdef51893080ec771a87b03afca0f48c07c4f157f7856ebbc092ea1c762c461bc6b19c9bc8bd6eecb2814
  
test:
  secret_key_base: 06b15944f9704bf8cc710891a144ddfb4fffcfacc050db16bc93dddcfcdc6eda76cb05f69da28a00d5b899262e491b10d3f09ea26b74c1eaa280fdd75c64c877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
